"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class arm_command(object):
    """
    机械臂运动指令 (主控发布, 接收端订阅后翻译成 move_pose/move_joint)。
    平移单位: 米。t_ee2base 行优先 4x4。
    """

    __slots__ = ["cmd_id", "t_ee2base", "speed", "accel", "block"]

    __typenames__ = ["int64_t", "double", "double", "double", "boolean"]

    __dimensions__ = [None, [16], None, None, None]

    def __init__(self):
        self.cmd_id = 0
        """ LCM Type: int64_t """
        self.t_ee2base = [ 0.0 for dim0 in range(16) ]
        """
        指令 id, 主控自增; 接收端执行完后用相同 id 回 execution_feedback
        LCM Type: double[16]
        """

        self.speed = 0.0
        """
        末端目标位姿 4x4 (行优先)
        LCM Type: double
        """

        self.accel = 0.0
        """
        0..1
        LCM Type: double
        """

        self.block = False
        """
        0..1
        LCM Type: boolean
        """


    def encode(self):
        buf = BytesIO()
        buf.write(arm_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.cmd_id))
        buf.write(struct.pack('>16d', *self.t_ee2base[:16]))
        buf.write(struct.pack(">ddb", self.speed, self.accel, self.block))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_command()
        self.cmd_id = struct.unpack(">q", buf.read(8))[0]
        self.t_ee2base = struct.unpack('>16d', buf.read(128))
        self.speed, self.accel = struct.unpack(">dd", buf.read(16))
        self.block = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_command in parents: return 0
        tmphash = (0x84b21fb3fe2e30b7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_command._packed_fingerprint is None:
            arm_command._packed_fingerprint = struct.pack(">Q", arm_command._get_hash_recursive([]))
        return arm_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_command._get_packed_fingerprint())[0]

