"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ee_pose(object):
    """
    末端位姿 (桥发布, 主控订阅)。
    桥把 lbot 的 /pose_states (ROS) 实时转发成此 LCM 消息, 主控订阅缓存,
    拍照时取最新值即 T_gripper2base, 无需依赖 ROS。
    t_ee2base 行优先 4x4, 平移米。
    """

    __slots__ = ["timestamp", "t_ee2base"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, [16]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.t_ee2base = [ 0.0 for dim0 in range(16) ]
        """
        发布时刻 (epoch 秒)
        LCM Type: double[16]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(ee_pose._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.timestamp))
        buf.write(struct.pack('>16d', *self.t_ee2base[:16]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ee_pose._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ee_pose._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ee_pose()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.t_ee2base = struct.unpack('>16d', buf.read(128))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ee_pose in parents: return 0
        tmphash = (0xcaf56da4a381798f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ee_pose._packed_fingerprint is None:
            ee_pose._packed_fingerprint = struct.pack(">Q", ee_pose._get_hash_recursive([]))
        return ee_pose._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ee_pose._get_packed_fingerprint())[0]

