"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class execution_feedback(object):
    """
    执行反馈 (接收端发布, 主控订阅)。
    接收端执行完一条 arm_command/hand_command 后, 用相同的 cmd_id 回此消息。
    主控用它实现阻塞: 发指令 -> 等对应 cmd_id 的 feedback -> 继续。
    """

    __slots__ = ["cmd_id", "success", "error"]

    __typenames__ = ["int64_t", "boolean", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.cmd_id = 0
        """ LCM Type: int64_t """
        self.success = False
        """
        对应所完成指令的 cmd_id
        LCM Type: boolean
        """

        self.error = ""
        """
        是否执行成功
        LCM Type: string
        """


    def encode(self):
        buf = BytesIO()
        buf.write(execution_feedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.cmd_id, self.success))
        __error_encoded = self.error.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_encoded)+1))
        buf.write(__error_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != execution_feedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return execution_feedback._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = execution_feedback()
        self.cmd_id = struct.unpack(">q", buf.read(8))[0]
        self.success = bool(struct.unpack('b', buf.read(1))[0])
        __error_len = struct.unpack('>I', buf.read(4))[0]
        self.error = buf.read(__error_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if execution_feedback in parents: return 0
        tmphash = (0xd57d05f0273017e0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if execution_feedback._packed_fingerprint is None:
            execution_feedback._packed_fingerprint = struct.pack(">Q", execution_feedback._get_hash_recursive([]))
        return execution_feedback._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", execution_feedback._get_packed_fingerprint())[0]

