"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hand_command(object):
    """
    灵巧手运动指令 (主控发布, 接收端订阅后翻译成 set_l6_joint 等)。
    positions: 各指位置 0..255。
    """

    __slots__ = ["cmd_id", "n_dof", "positions"]

    __typenames__ = ["int64_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, ["n_dof"]]

    def __init__(self):
        self.cmd_id = 0
        """ LCM Type: int64_t """
        self.n_dof = 0
        """
        与 arm_command.cmd_id 同机制
        LCM Type: int16_t
        """

        self.positions = []
        """
        手指数 (如 6 / 10)
        LCM Type: int16_t[n_dof]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(hand_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.cmd_id, self.n_dof))
        buf.write(struct.pack('>%dh' % self.n_dof, *self.positions[:self.n_dof]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hand_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hand_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hand_command()
        self.cmd_id, self.n_dof = struct.unpack(">qh", buf.read(10))
        self.positions = struct.unpack('>%dh' % self.n_dof, buf.read(self.n_dof * 2))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hand_command in parents: return 0
        tmphash = (0xbc29e9bd9ce2c85) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hand_command._packed_fingerprint is None:
            hand_command._packed_fingerprint = struct.pack(">Q", hand_command._get_hash_recursive([]))
        return hand_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hand_command._get_packed_fingerprint())[0]

