"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class joint_command(object):
    """
    关节空间运动指令 (主控发布, 接收端订阅后翻译成 move_joint)。
    用于 WARMUP/COOLDOWN: 关节空间路径可控, 避开笛卡尔插值可能触发的奇异/碰撞。
    joints: 7 关节角 (弧度)。
    """

    __slots__ = ["cmd_id", "joints", "speed", "accel", "block"]

    __typenames__ = ["int64_t", "double", "double", "double", "boolean"]

    __dimensions__ = [None, [7], None, None, None]

    def __init__(self):
        self.cmd_id = 0
        """ LCM Type: int64_t """
        self.joints = [ 0.0 for dim0 in range(7) ]
        """
        与 arm_command.cmd_id 同机制 (配 execution_feedback 阻塞)
        LCM Type: double[7]
        """

        self.speed = 0.0
        """
        7 关节角 (弧度)
        LCM Type: double
        """

        self.accel = 0.0
        """
        0..1
        LCM Type: double
        """

        self.block = False
        """
        0..1
        LCM Type: boolean
        """


    def encode(self):
        buf = BytesIO()
        buf.write(joint_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.cmd_id))
        buf.write(struct.pack('>7d', *self.joints[:7]))
        buf.write(struct.pack(">ddb", self.speed, self.accel, self.block))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_command()
        self.cmd_id = struct.unpack(">q", buf.read(8))[0]
        self.joints = struct.unpack('>7d', buf.read(56))
        self.speed, self.accel = struct.unpack(">dd", buf.read(16))
        self.block = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_command in parents: return 0
        tmphash = (0xfcb4eecc62596cfa) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_command._packed_fingerprint is None:
            joint_command._packed_fingerprint = struct.pack(">Q", joint_command._get_hash_recursive([]))
        return joint_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_command._get_packed_fingerprint())[0]

